### ISSUE TITLE
Maximum call Stack exceeded when calling decodeMultiple in a service worker in Edge Browser

### ISSUE THREAD

**Issue by PhilWhitehurst** [kriszyp/cbor-x#101]
Trying to use cbor-x to send values to browser and when trying to decode I get this when using a fetch inside a service worker, and decodeMultiple for the response.

RangeError: Maximum call stack size exceeded
    at decodeMultiple (decode.js:193:4)
    at decodeMultiple (decode.js:167:28)
    at decodeMultiple (decode.js:167:28)
    at decodeMultiple (decode.js:167:28)
    at decodeMultiple (decode.js:167:28)
    at decodeMultiple (decode.js:167:28)
    at decodeMultiple (decode.js:167:28)
    at decodeMultiple (decode.js:167:28)
    at decodeMultiple (decode.js:167:28)
    at decodeMultiple (decode.js:167:28)

**Comment by kriszyp** [comment]
Do you have any information on how to reproduce this? I can't reproduce, this line number doesn't match up with a call to decodeMultiple.
