### ISSUE TITLE
TypeError: newPackedValues.concat is not a function

### ISSUE THREAD

**Issue by hans00** [kriszyp/cbor-x#93]
I got this error.

```
TypeError: newPackedValues.concat is not a function
    at packedTable (/app/node_modules/cbor-x/dist/node.cjs:866:48)
    at read (/app/node_modules/cbor-x/dist/node.cjs:415:13)
    at checkedRead (/app/node_modules/cbor-x/dist/node.cjs:201:16)
    at Decoder.decodeMultiple (/app/node_modules/cbor-x/dist/node.cjs:185:18)
    at DecoderStream._transform (/app/node_modules/cbor-x/dist/node.cjs:2388:26)
    at Transform._write (node:internal/streams/transform:175:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at IncomingMessage.ondata (node:internal/streams/readable:777:22)
```

But currently not sure what payload cause this error. (It might be broken file.)

**Comment by hans00** [comment]
I found the problem.
The file is ok, but internet transfer chunk size may cause this bug.

And also `Packed values structure must be followed by a 4 element array`

**Comment by hans00** [comment]
I could reproduce by very small water mark `createReadStream(file, { highWaterMark: 10 })`.
And seems could mitigate with a middle buffer.
